SHELL := /bin/bash

apply-pod:
	kubectl apply -f pod.yaml

apply-from-url:
	kubectl apply -f https://raw.githubusercontent.com/sixeyed/kiamol/master/ch02/pod.yaml

apply-deployment:
	kubectl apply -f deployment.yaml
